name: Diasporas Blog
url: "http://diasporas.cc"
description: "Collecting the dots for diasporas"
markdown: redcarpet
highlighter: true
timezone: America/Los_Angeles
exclude:
  - less
  - workspace
  - design
